version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - env
      - which aws
      - aws --version
      - pip install --upgrade pip
      - pip install ansible
      - aws s3 cp s3://tudublin-ca-aws-keys/tudublin.pem /root/.ssh/tudublin.pem
      - chmod 400 /root/.ssh/tudublin.pem
  pre_build:
    commands:
      - echo $AWSRegion
      - aws cloudformation validate-template --template-body file://infranstructure.yaml --region $AWSRegion
  build:
    commands:
      - aws cloudformation deploy --region $AWSRegion --stack-name $BRANCH --template-file infranstructure.yaml --parameter-overrides KeyName=$KeyName,AMI=$AMI,InstanceName=$InstanceName,SubnetId=$SubnetId,InstanceType=$InstanceType,VPCId=$VPCId
      - aws cloudformation wait stack-create-complete --stack-name $BRANCH --region $AWSRegion
      - export PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name $CODEBUILD_SOURCE_VERSION --query "Stacks[0].Outputs[?OutputKey=='PublicIP'].OutputValue" --output text)
      - ssh-keyscan -H $PUBLIC_IP >> ~/.ssh/known_hosts
      - echo "[web]" > inventory.ini
      - echo "$PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/tudublin.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini
  post_build:
    commands:
      - echo "Stack deployment complete."
artifacts:
  files:
    - '**/*'
  discard-paths: yes
