---

- hosts: all
  become: true

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create weather app directory
      file:
        path: /home/ubuntu/weather-app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy code to the server
      copy:
        src: .
        dest: /home/ubuntu/weather-app

    - name: Install python
      apt:
        name: python3
        state: present
        update_cache: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install python venv
      apt:
        name: python3-venv
        state: present
        update_cache: yes

    - name: Create python venv
      command: python3 -m venv /home/ubuntu/weather-app/.venv
    
    - name: Install requirements
      command: /home/ubuntu/weather-app/.venv/bin/pip install -r /home/ubuntu/weather-app/requirements.txt

    - name: Copy systemd service file
      copy:
        src: weather-app.service
        dest: /etc/systemd/system/weather-app.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start weather app
      systemd:
        name: weather-app
        state: started
        enabled: yes
      
    - name: Create nginx configuration
      copy:
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:5000;
              }
          }
        dest: /etc/nginx/sites-available/default
      notify:
        - reload nginx

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
